ldksyahid/ldksyahid-app

README.md

Feature ldk 001

---

README.md

[RELEASE] Add Release Notes

---

resources/views/errors/503.blade.php

[ENHANCEMENT] Change Logo Image Maintenance

[ENHANCEMENT] Change Logo Image Maintenance

---

README.md

[ENHANCEMENT] Change Readme

---

app/Http/Controllers/JumbotronController.php
resources/views/admin-page/about/gallery/index.blade.php
resources/views/admin-page/about/it-support/index.blade.php
resources/views/admin-page/about/management-structure/index.blade.php
resources/views/admin-page/article/index.blade.php
resources/views/admin-page/dashboard/index.blade.php
resources/views/admin-page/event/index.blade.php
resources/views/admin-page/home/jumbotron/create.blade.php
resources/views/admin-page/home/jumbotron/index.blade.php
resources/views/admin-page/home/jumbotron/update.blade.php
resources/views/admin-page/home/jumbotron/view.blade.php
resources/views/admin-page/home/testimony/index.blade.php
resources/views/admin-page/news/index.blade.php
resources/views/admin-page/schedule/index.blade.php
resources/views/admin-page/service/celengan-syahid/campaign/index.blade.php

Feature ldk 013

---

app/Http/Controllers/DashboardController.php
resources/views/admin-page/dashboard/index.blade.php

[ENHANCEMENT] Remove Visitor count in dashboar d index admin

[ENHANCEMENT] Remove Visitor count in dashboar d index admin

---

app/Http/Controllers/DashboardController.php
app/Http/Controllers/HomeController.php
resources/views/admin-page/dashboard/index.blade.php

[[ISSUE] Fixing Dashboard Index Admin](https://github.com/ldksyahid/ldksyahid-app/commit/2ed6e7a301bb0a8206a1dc13aef79ea6e995cf09)

[ISSUE] Fixing Dashboard Index Admin

---

resources/views/admin-page/dashboard/index.blade.php

[ENHANCEMENT] Change Position Location

[ENHANCEMENT] Change Position Location

---

resources/views/auth/verify.blade.php
resources/views/landing-page/home/partials/about.blade.php
resources/views/landing-page/home/partials/article.blade.php
resources/views/landing-page/home/partials/contact-us.blade.php
resources/views/landing-page/home/partials/event.blade.php
resources/views/landing-page/home/partials/gallery.blade.php
resources/views/landing-page/home/partials/jumbotron.blade.php
resources/views/landing-page/home/partials/kmb-class.blade.php
resources/views/landing-page/home/partials/news.blade.php
resources/views/landing-page/home/partials/schedule.blade.php
resources/views/landing-page/home/partials/testimony.blade.php
resources/views/landing-page/template/footer.blade.php

[ENHANCEMENT] Change Design Layout Landing Page (Beranda) type Desktop

[ENHANCEMENT] Change Design Layout Landing Page (Beranda) type Desktop

---

app/Http/Controllers/Auth/LoginController.php
resources/views/auth/login.blade.php
resources/views/auth/passwords/confirm.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/auth/register.blade.php
resources/views/emails/celengan-syahid/donation-invoice.blade.php

[ENHANCEMNENT] Revamp Page Auth

[ENHANCEMNENT] Revamp Page Auth

---

resources/views/landing-page/service/short-link/index.blade.php

feat: change pj service shortlink

feat: change pj service shortlink

---

resources/views/admin-page/service/short-link/index.blade.php

[ENHANVEMENT] add show counter pagination

[ENHANVEMENT] add show counter pagination

---

resources/views/admin-page/service/short-link/index.blade.php

[ENHANCEMENT] add border radius table short link

[ENHANCEMENT] add border radius table short link

---

app/Http/Controllers/ShortLinkController.php
resources/views/admin-page/service/short-link/index.blade.php

[ENHANCEMENT] add validate url update shortlink

[ENHANCEMENT] add validate url update shortlink

---

resources/views/admin-page/service/short-link/index.blade.php

[ENHANCEMEMENT] change sentence

[ENHANCEMEMENT] change sentence

---

resources/views/admin-page/service/short-link/index.blade.php

[ENHANCEMENT] change top potsition

[ENHANCEMENT] change top potsition

---

app/Http/Controllers/ShortLinkController.php
resources/views/admin-page/service/short-link/index.blade.php

feat: add dropdown search visitor in shortlink

feat: add dropdown search visitor in shortlink

---

resources/views/landing-page/template/nav-bar.blade.php

feat: comment menu katalog buku

feat: comment menu katalog buku

---

resources/views/landing-page/template/footer.blade.php

feat: remove mt in footer

---

resources/views/landing-page/ekspresi/template/body.blade.php

feat: change title eskpresi

---

resources/views/landing-page/ekspresi/_index-styles.blade.php
resources/views/landing-page/ekspresi/index.blade.php
resources/views/landing-page/ekspresi/template/nav-bar.blade.php

[feat: change content ekspresi 2025](https://github.com/ldksyahid/ldksyahid-app/commit/4f352274f3dffcf17508656cbbe23976ca669f23)

feat: change content ekspresi 2025
